## AIdiva -- Augmented Intelligence Disease Variant Analysis
# Configuration file specifiying all the parameters that are needed to run AIdiva in the different modes
# if you modify the key names make sure to also update them in the run_AIdiva.py script
---
Analysis-Input:
    # if inheritance should be considered and family information is provided, make sure that the vcf file contains sample informations for all family members,
    # else sample will be treated as single patient with unknown inheritance
    vcf: /home/dominic/Masterarbeit/test_complete_pipeline/trio_variant_call_simulated_variant_recessive_stripped_vep.vcf
    
    # trained scoring models used to predict the pathogenicity score
    # if no trained model is present you can use the train_model.py script to train a new custom model
    scoring-model-snps: /home/dominic/Masterarbeit/test_complete_pipeline/rf-clf_ownDB_origModel_origFeatures.pkl
    #scoring-model-indels: data/rf_model_indels.pkl
    
    inheritance-information:
        # file containing the HPO terms that are associated with the disease (one term per line)
        hpo-file: /home/dominic/Masterarbeit/test_complete_pipeline/recessive_HPO.txt
        
        # inheritance of the disease if known and family type not SINGLE is given
        # possible values: [RECESSIVE, COMPOUND, DOMINANT_DENOVO, DOMINANT_INHERITED, XLINKED, UNKNOWN]
        inheritance: recessive
        
        # family type, shows the structure of the given family inforamtion
        # possible values: [TRIO, FAMILY, SINGLE]
        family-type: trio
        
        # file with the family information
        family-file: /home/dominic/Masterarbeit/test_complete_pipeline/family.txt
        
        # List of genes that should be excluded in the analysis, because they are normally false positives
        # a default list is given in the res/ folder (gene_exclusion_list.txt), the file can be empty
        gene-exclusion: /home/dominic/Masterarbeit/test_complete_pipeline/empty_list.txt

Additional-Annotation:
    # ABB_score
    abb-score: /home/dominic/Masterarbeit/databases/ABB_SCORE.txt
    
    # Simple tandem repeats
    simple-repeats: /home/dominic/Masterarbeit/databases/simpleRepeat.txt
    
    # Segment Duplication
    segment-duplication: /home/dominic/Masterarbeit/databases/genomicSuperDups.txt
    
    # additional annotations the key is used as feature name for the prediction
    additional-bigwig-files:
        phyloP46_mammal: /home/dominic/Masterarbeit/databases/phastCons46way.placentalMammal.complete.onlyChrom.bw
        phyloP46_primate: /home/dominic/Masterarbeit/databases/phastCons46way.primate.complete.onlyChrom.bw
        phyloP46_vertebrate: /home/dominic/Masterarbeit/databases/phastCons46way.vertebrate.complete.onlyChrom.bw
        phastCons46_mammal: /home/dominic/Masterarbeit/databases/phastCons46way.placentalMammal.complete.onlyChrom.bw
        phastCons46_primate: /home/dominic/Masterarbeit/databases/phastCons46way.primate.complete.onlyChrom.bw
        phastCons46_vertebrate: /home/dominic/Masterarbeit/databases/phastCons46way.vertebrate.complete.onlyChrom.bw

    
Analysis-Output:
    tsv: /home/dominic/Masterarbeit/test_complete_pipeline/test_recessive_full_tempfile.tsv
    tsv-filt: /home/dominic/Masterarbeit/test_complete_pipeline/test_recessive_full_filtered_tempfile.tsv

    
Internal-Parameters:
